### ISSUE TITLE
File <input> cannot be opened

### ISSUE THREAD

**Issue by ahsandar** [o5/apib2json#5]
I keep getting `File <input> cannot be opened` any idea what could be the causes for this. I can generate HTML using snowboard from the `apib` file and and also checked for any error all looks good. 

https://github.com/o5/apib2json/blob/44b0559a6d3ca4d9143ae068695f1291f5d88015/bin/apib2json#L61

**Comment by ahsandar** [comment]
when i do `docker-compose up` and go into the container to run `apib2json` I get the following error 

```internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/src/apib2json/apib2json/bin/apib2json:14:17)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)```

so can't run to print the stack trace for the error

**Comment by o5** [comment]
Hi @ahsandar 

ad `File <input> cannot be opened`: please attach the command which you ran

ad `Error: Cannot find module 'commander'`: I've tried and cannot reproduce

**Comment by ahsandar** [comment]
ad File <input> cannot be opened: please attach the command which you ran
`docker run -it --rm  bugyik/apib2json --pretty --input $PWD/genzo/docs/genzo-api.apib --output $PWD/genzo/docs/output/genzo-api-schema.json`

ad Error: Cannot find module 'commander': I've tried and cannot reproduce
> `docker-compse up`
>  `docker exec -it apib2json sh`
> `node apib2json` (from anywhere or from the apib2json/bin)

**Comment by o5** [comment]
1. It's because you're using dockerized version and your `--input` is not inside of container. You have to use `<`, `>` in this case.
1. `node apib2json` is wrong. Try only `apib2json`
